import { authenticatedFetchWithRefresh, buildUrl } from '../utils/api';
import { Event, EventTicket } from '../types/events';
import { Share } from 'react-native';

export interface TicketPDFData {
  eventId: string;
  ticketId: string;
  eventTitle: string;
  eventDate: string;
  eventTime: string;
  venue: string;
  city: string;
  qrCode: string;
  ticketStatus: string;
}

/**
 * Generate and email a PDF ticket to the user
 * @param event - The event details
 * @param ticket - The ticket details
 * @param qrData - The QR code data string
 * @returns Promise<{ success: boolean, message: string }>
 */
export const generateAndEmailTicketPDF = async (
  event: Event,
  ticket: EventTicket,
  qrData: string
): Promise<{ success: boolean, message: string }> => {
  try {
    // Format the event date and time
    const eventDate = event.eventDateISO ? new Date(event.eventDateISO) : new Date(event.eventDate);
    const formattedDate = eventDate.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    const formattedTime = eventDate.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
    });

    // Prepare the ticket data
    const ticketData: TicketPDFData = {
      eventId: event.id,
      ticketId: ticket.id,
      eventTitle: event.title,
      eventDate: formattedDate,
      eventTime: formattedTime,
      venue: event.location.venue,
      city: event.location.city,
      qrCode: qrData,
      ticketStatus: ticket.status,
    };

    console.log('[TicketService] Generating PDF ticket for:', ticketData.eventTitle);

    // Send request to backend to generate and email PDF
    const response = await authenticatedFetchWithRefresh('/api/tickets/generate-pdf-email', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(ticketData),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.message || 'Failed to generate PDF ticket');
    }

    const result = await response.json();
    
    if (result.success) {
      console.log('[TicketService] PDF ticket generated and emailed successfully');
      return {
        success: true,
        message: 'Ticket PDF has been sent to your email address',
      };
    } else {
      throw new Error(result.message || 'Failed to generate PDF ticket');
    }
  } catch (error) {
    console.error('[TicketService] Error generating PDF ticket:', error);
    return {
      success: false,
      message: error instanceof Error ? error.message : 'Failed to generate PDF ticket',
    };
  }
};

/**
 * Share ticket information as text
 * @param event - The event details
 * @param ticket - The ticket details
 */
export const shareTicketInfo = async (event: Event, ticket: EventTicket): Promise<void> => {
  try {
    const eventDate = event.eventDateISO ? new Date(event.eventDateISO) : new Date(event.eventDate);
    const formattedDate = isNaN(eventDate.getTime()) ? 'Date TBD' : eventDate.toLocaleDateString();
    
    const shareContent = `My XSCard Event Ticket

Event: ${event.title}
Date: ${formattedDate}
Venue: ${event.location.venue}
City: ${event.location.city}

Ticket ID: ${ticket.id}
Status: ${ticket.status.toUpperCase()}

Generated by XSCard App`;

    await Share.share({
      message: shareContent,
      title: `XSCard Event Ticket - ${event.title}`,
    });
  } catch (error) {
    console.error('[TicketService] Error sharing ticket:', error);
  }
}; 